---
apiVersion: v1
kind: Pod
metadata:
  name: nfs2
spec:
  containers:
    - name: app2
      image: alpine
      volumeMounts:
      - name: data
        mountPath: /mnt/nfs
      command: ["/bin/sh"]
      args: ["-c", "sleep 500000"]
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: testpvc