- name: Worker k8s config
  hosts: worker_nodes
  become: true

  tasks:
    - name: Update package lists, upgrade packages, and install packages
      apt:
        update_cache: yes
        name:
          - curl
          - apt-transport-https
          - git
          - iptables-persistent
        state: present
    
    - name: Add modules to k8s.conf
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: "{{ item }}"
        create: yes
      with_items:
        - br_netfilter
        - overlay
    
    - name: Load br_netfilter module
      shell: sudo modprobe br_netfilter

    - name: Load overlay module
      shell: sudo modprobe overlay
    # setup br Tables
    - name: Create sysctl configuration file
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables=1
        net.bridge.bridge-nf-call-iptables=1
        net.ipv4.ip_forward=1
        EOF
      changed_when: false

    - name: Load sysctl configuration
      command: sudo sysctl --system
    # off the Swap
    - name: Comment out swap entry
      replace:
        path: /etc/fstab
        regexp: '^(\/swap\.img.*)$'
        replace: '# \1'
    
    - name: Load overlay module
      shell: sudo swapoff -a
    
    # - name: for master nodes
    #   shell: iptables -I INPUT 1 -p tcp --match multiport --dports 6443,2379:2380,10250:10252 -j ACCEPT
    
    - name: for sub nodes
      shell: iptables -I INPUT 1 -p tcp --match multiport --dports 10250,30000:32767 -j ACCEPT
    
    - name: Save Iptables rules
      shell: netfilter-persistent save
