apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tolik
  namespace: project1
subjects:
- kind: User
  name: tolik
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
