apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eduardo-proj1
  namespace: project1
subjects:
- kind: User
  name: eduardo
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eduardo-proj2
  namespace: project2
subjects:
- kind: User
  name: eduardo
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
